/*
 * generated by Xtext
 */
package de.nordakademie.ticket.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TicketUiModule extends de.nordakademie.ticket.ui.AbstractTicketUiModule {
	public TicketUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
