/*
 * generated by Xtext
 */
package de.nordakademie.ticket.ui.contentassist

import de.nordakademie.ticket.ui.contentassist.AbstractTicketProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TicketProposalProvider extends AbstractTicketProposalProvider {
}
