/*
 * generated by Xtext
 */
package de.nordakademie.ticket;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TicketRuntimeModule extends de.nordakademie.ticket.AbstractTicketRuntimeModule {

}
