/*
 * generated by Xtext
 */
package de.nordakademie.ticket;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TicketStandaloneSetup extends TicketStandaloneSetupGenerated{

	public static void doSetup() {
		new TicketStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

